name: Deploy to Modal

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 18 * * *'
  repository_dispatch:
    types: [service-down-alert]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODAL_USER_NAME: ${{ secrets.MODAL_USER_NAME || 'frankjsw'}}
      MODAL_APP_NAME: ${{ secrets.MODAL_APP_NAME || 'frankjsw' }}
      SUB_PATH: ${{ secrets.SUB_PATH || 'sub' }}
      SERVER_PORT: ${{ secrets.SERVER_PORT || '3000' }}
      
    steps:
      - name: Check Trigger Event
        run: |
          echo "Workflow triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "触发事件类型 (Event Type): ${{ github.event.action }}"
            echo "收到来自 Uptime Kuma 的下线通知，开始执行自动恢复部署流程..."
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "工作流被手动触发，开始执行部署..."
          else
            echo "工作流由计划任务触发，开始执行部署..."
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install modal fastapi requests

      - name: Authenticate Modal
        run: |
          modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Stop Existing App (for clean deploy)
        run: |
          modal app stop ${{ env.MODAL_APP_NAME }} || true

      - name: Create or Update Modal Secret
        run: |
          modal secret delete modal-secrets --yes || true
          
          modal secret create modal-secrets \
          UUID='${{ secrets.UUID || 'eea64bd2-dd10-458f-a31a-0a687cdde8e4' }}' \
          MODAL_USER_NAME='${{ secrets.MODAL_USER_NAME || 'frankjsw'}}' \
          ARGO_DOMAIN='${{ secrets.ARGO_DOMAIN || 'modal.1.2.9.b.0.d.0.0.1.0.a.2.ip6.arpa'}}' \
          ARGO_AUTH='${{ secrets.ARGO_AUTH || 'eyJhIjoiNjU4NTBjYjUzOTUyZjNhNTEwNThiOTEwMWVlYjMzY2QiLCJ0IjoiODlhMTA4OGQtNTliZS00ZjhkLWI2N2EtMDE2ZmE2YWNlZWVmIiwicyI6Ik5qQmxNbVZqTldJdFltSmlOQzAwTW1ZeUxUazFPREF0Wm1OaFltUXdaVGRtTTJReCJ9'}}' \
          ARGO_PORT='${{ secrets.ARGO_PORT || '8009' }}' \
          SUB_PATH='${{ secrets.SUB_PATH || 'sub' }}' \
          NAME='${{ secrets.NAME || 'modal' }}' \
          CFIP='${{ secrets.CFIP || 'www.visa.com.tw' }}' \
          CFPORT='${{ secrets.CFPORT || '443' }}' \
          NEZHA_SERVER='${{ secrets.NEZHA_SERVER }}' \
          NEZHA_KEY='${{ secrets.NEZHA_KEY }}' \
          NEZHA_PORT='${{ secrets.NEZHA_PORT }}' \
          UPLOAD_URL='${{ secrets.UPLOAD_URL }}' \
          PROJECT_URL='${{ secrets.PROJECT_URL }}' \
          BOT_TOKEN='${{ secrets.BOT_TOKEN }}' \
          CHAT_ID='${{ secrets.CHAT_ID }}'

      - name: Deploy to Modal
        run: modal deploy modal_app.py

      - name: Output Deployment URLs
        run: |
          echo "✅ 部署成功!"
          echo "--------------------------------------------------"
          echo "项目 URL: https://${{ env.MODAL_USER_NAME }}--${{ env.MODAL_APP_NAME }}-web_server.modal.run"
          echo "订阅 URL: https://${{ env.MODAL_USER_NAME }}--${{ env.MODAL_APP_NAME }}-web_server.modal.run/${{ env.SUB_PATH }}"
          echo "--------------------------------------------------"
